### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [gipsonsa/Week_10_Rails#1]
Looks good apart from [one little indentation issue in `static.scss`](https://github.com/gipsonsa/Week_10_Rails/blob/master/app/assets/stylesheets/static.scss#L6). The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated this and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by gipsonsa** [comment]
Hello Chris,

So I went into the preferences, added that line of code to my USER settings and even went to re-write that bit of code so that it would have correct indentation. However it still won’t budge.

Could it be that when I change my preferences in Sublime I get this? I think it has something to do with me having sublime text 2

Sam

**Comment by gipsonsa** [comment]
Wait I fixed it I think, haha there was something going on with an author problem? I’m not sure how to explain it but I think my project would be up to date now.

**Comment by chrisvfritz** [comment]
:+1: Looks great!
